/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.maquinadedoce;

/**
 *
 * @author USER
 */
public class TelaMaquina extends javax.swing.JFrame {

    /**
     * Creates new form TelaMaquina
     */
    public TelaMaquina() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MaquinaDeDoce MaquinaDeDoce = new MaquinaDeDoce();

        lbl_titulo = new javax.swing.JLabel();
        Painel_DoceA = new javax.swing.JPanel();
        img_DoceA = new javax.swing.JLabel();
        lbl_precoDoceA = new javax.swing.JLabel();
        btn_doceA = new javax.swing.JButton();
        Painel_DoceB = new javax.swing.JPanel();
        img_DoceB = new javax.swing.JLabel();
        lbl_precoDoceB = new javax.swing.JLabel();
        btn_DoceB = new javax.swing.JButton();
        Painel_DoceC = new javax.swing.JPanel();
        img_DoceC = new javax.swing.JLabel();
        lbl_precoDoceC = new javax.swing.JLabel();
        btn_doceC = new javax.swing.JButton();
        lbl_prefixo = new javax.swing.JLabel();
        lbl_saldo = new javax.swing.JLabel();
        lbl_inserir = new javax.swing.JLabel();
        btn_1_real = new javax.swing.JButton();
        btn_2_real = new javax.swing.JButton();
        btn_5_real = new javax.swing.JButton();
        lbl_retirarSaldo = new javax.swing.JLabel();
        btn_resgatar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Máquina de Doces");

        lbl_titulo.setFont(new java.awt.Font("Showcard Gothic", 2, 36)); // NOI18N
        lbl_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_titulo.setText("MÁQUINA DE DOCES");
        lbl_titulo.setToolTipText("");
        lbl_titulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        img_DoceA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/maquinadedoce/balaA.png"))); // NOI18N

        lbl_precoDoceA.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lbl_precoDoceA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_precoDoceA.setText("R$ 6.00");
        lbl_precoDoceA.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btn_doceA.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        btn_doceA.setText("BOMBOM");
        btn_doceA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_doceAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Painel_DoceALayout = new javax.swing.GroupLayout(Painel_DoceA);
        Painel_DoceA.setLayout(Painel_DoceALayout);
        Painel_DoceALayout.setHorizontalGroup(
            Painel_DoceALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(img_DoceA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_precoDoceA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_doceA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Painel_DoceALayout.setVerticalGroup(
            Painel_DoceALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_DoceALayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(img_DoceA, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_precoDoceA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_doceA))
        );

        img_DoceB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/maquinadedoce/novotrident.png"))); // NOI18N

        lbl_precoDoceB.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lbl_precoDoceB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_precoDoceB.setText("R$ 7.00");

        btn_DoceB.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        btn_DoceB.setText("TRIDENT");
        btn_DoceB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DoceBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Painel_DoceBLayout = new javax.swing.GroupLayout(Painel_DoceB);
        Painel_DoceB.setLayout(Painel_DoceBLayout);
        Painel_DoceBLayout.setHorizontalGroup(
            Painel_DoceBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_DoceBLayout.createSequentialGroup()
                .addGroup(Painel_DoceBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_precoDoceB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Painel_DoceBLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(img_DoceB))
                    .addComponent(btn_DoceB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(43, 43, 43))
        );
        Painel_DoceBLayout.setVerticalGroup(
            Painel_DoceBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_DoceBLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(img_DoceB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_precoDoceB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_DoceB))
        );

        img_DoceC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/maquinadedoce/alfajor.png"))); // NOI18N

        lbl_precoDoceC.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lbl_precoDoceC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_precoDoceC.setText("R$ 8.00");

        btn_doceC.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        btn_doceC.setText("ALFAJOR");
        btn_doceC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_doceCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Painel_DoceCLayout = new javax.swing.GroupLayout(Painel_DoceC);
        Painel_DoceC.setLayout(Painel_DoceCLayout);
        Painel_DoceCLayout.setHorizontalGroup(
            Painel_DoceCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_doceC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_precoDoceC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Painel_DoceCLayout.createSequentialGroup()
                .addComponent(img_DoceC)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Painel_DoceCLayout.setVerticalGroup(
            Painel_DoceCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_DoceCLayout.createSequentialGroup()
                .addComponent(img_DoceC, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_precoDoceC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_doceC))
        );

        lbl_prefixo.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lbl_prefixo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_prefixo.setText("SALDO: R$");

        lbl_saldo.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lbl_saldo.setText(MaquinaDeDoce.getValor() + ".00");

        lbl_inserir.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lbl_inserir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_inserir.setText("INSERIR");

        btn_1_real.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        btn_1_real.setText("1 REAL");
        btn_1_real.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1_realActionPerformed(evt);
            }
        });

        btn_2_real.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        btn_2_real.setText("2 REAIS");
        btn_2_real.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2_realActionPerformed(evt);
            }
        });

        btn_5_real.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        btn_5_real.setText("5 REAIS");
        btn_5_real.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_5_realActionPerformed(evt);
            }
        });

        lbl_retirarSaldo.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lbl_retirarSaldo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_retirarSaldo.setText("RETIRAR SALDO");

        btn_resgatar.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        btn_resgatar.setText("RESGATAR");
        btn_resgatar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_resgatar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resgatarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Painel_DoceA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Painel_DoceB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Painel_DoceC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(lbl_prefixo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_2_real, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_1_real, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_5_real, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_inserir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_saldo)
                    .addComponent(btn_resgatar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_retirarSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Painel_DoceB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Painel_DoceC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Painel_DoceA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_prefixo)
                            .addComponent(lbl_saldo))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lbl_inserir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                                .addComponent(btn_1_real)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_resgatar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_2_real, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_5_real)
                                .addGap(42, 42, 42))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(lbl_retirarSaldo)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_doceAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_doceAActionPerformed
        try {
            MaquinaDeDoce MaquinaDeDoce = new MaquinaDeDoce();
            MaquinaDeDoce.pedirDoce(6);
            dispose();
            TelaMaquina TelaMaquina = new TelaMaquina();
            TelaMaquina.setVisible(true);
        } catch (Exception e) {
            // TODO: handle exception
        }
    }//GEN-LAST:event_btn_doceAActionPerformed

    private void btn_DoceBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DoceBActionPerformed
        try {
            MaquinaDeDoce MaquinaDeDoce = new MaquinaDeDoce();
            MaquinaDeDoce.pedirDoce(7);
            dispose();
            TelaMaquina TelaMaquina = new TelaMaquina();
            TelaMaquina.setVisible(true);
        } catch (Exception e) {
            // TODO: handle exception
        }
    }//GEN-LAST:event_btn_DoceBActionPerformed

    private void btn_doceCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_doceCActionPerformed
        try {
            MaquinaDeDoce MaquinaDeDoce = new MaquinaDeDoce();
            MaquinaDeDoce.pedirDoce(8);
            dispose();
            TelaMaquina TelaMaquina = new TelaMaquina();
            TelaMaquina.setVisible(true);
        } catch (Exception e) {
            // TODO: handle exception
        }
    }//GEN-LAST:event_btn_doceCActionPerformed

    private void btn_1_realActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1_realActionPerformed
        MaquinaDeDoce MaquinaDeDoce = new MaquinaDeDoce();
        MaquinaDeDoce.somaComVerif(1);
        dispose();
        TelaMaquina TelaMaquina = new TelaMaquina();
        TelaMaquina.setVisible(true);
    }//GEN-LAST:event_btn_1_realActionPerformed

    private void btn_2_realActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2_realActionPerformed
        MaquinaDeDoce MaquinaDeDoce = new MaquinaDeDoce();
        MaquinaDeDoce.somaComVerif(2);
        dispose();
        TelaMaquina TelaMaquina = new TelaMaquina();
        TelaMaquina.setVisible(true);
    }//GEN-LAST:event_btn_2_realActionPerformed

    private void btn_5_realActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_5_realActionPerformed
        MaquinaDeDoce MaquinaDeDoce = new MaquinaDeDoce();
        MaquinaDeDoce.somaComVerif(5);
        dispose();
        TelaMaquina TelaMaquina = new TelaMaquina();
        TelaMaquina.setVisible(true);
    }//GEN-LAST:event_btn_5_realActionPerformed

    private void btn_resgatarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resgatarActionPerformed
        try {
            MaquinaDeDoce MaquinaDeDoce = new MaquinaDeDoce();
            MaquinaDeDoce.resgatarSaldo();
            dispose();
            TelaMaquina TelaMaquina = new TelaMaquina();
            TelaMaquina.setVisible(true);
        } catch (Exception e) {
            // TODO: handle exception
        }
    }//GEN-LAST:event_btn_resgatarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMaquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMaquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMaquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMaquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMaquina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Painel_DoceA;
    private javax.swing.JPanel Painel_DoceB;
    private javax.swing.JPanel Painel_DoceC;
    private javax.swing.JButton btn_1_real;
    private javax.swing.JButton btn_2_real;
    private javax.swing.JButton btn_5_real;
    private javax.swing.JButton btn_DoceB;
    private javax.swing.JButton btn_doceA;
    private javax.swing.JButton btn_doceC;
    private javax.swing.JButton btn_resgatar;
    private javax.swing.JLabel img_DoceA;
    private javax.swing.JLabel img_DoceB;
    private javax.swing.JLabel img_DoceC;
    private javax.swing.JLabel lbl_inserir;
    private javax.swing.JLabel lbl_precoDoceA;
    private javax.swing.JLabel lbl_precoDoceB;
    private javax.swing.JLabel lbl_precoDoceC;
    private javax.swing.JLabel lbl_prefixo;
    private javax.swing.JLabel lbl_retirarSaldo;
    private javax.swing.JLabel lbl_saldo;
    private javax.swing.JLabel lbl_titulo;
    // End of variables declaration//GEN-END:variables
}
